base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.loginPage,name='login'),
    path('logout/',views.logoutPage,name='logout'),
    path('register/',views.registerPage,name='register'),
    path('room/<str:pk>/',views.room,name='room'),
    path('profile/<str:pk>/',views.userProfile,name='user-profile'),
    path('create-room/',views.createRoom,name='create-room'),
    path('update-room/<str:pk>',views.updateRoom,name='update-room'),
    path('delete-room/<str:pk>',views.deleteRoom,name='delete-room'),
    path('delete-message/<str:pk>',views.deleteMessage,name='delete-message'),
    path('update-profile/',views.updateProfile,name='update-profile'),
    path('topics/',views.topicsPage,name='topics'),
    path('activities/',views.activitiesPage,name='activities'),
    
]

studybud/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    name = models.CharField(max_length=200,null=True)
    email = models.EmailField(unique=True,null=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True,default='avatar.svg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    topic = models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    participants = models.ManyToManyField(User,related_name='participants',blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering= ['-updated','-created']

    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering= ['-updated','-created']

    def __str__(self):
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Room,User

class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name','username','email','password1','password2']

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host','participants']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar','name','username','email','bio']

base/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Room,Topic,Message,User
from .forms import RoomForm, UserForm,MyUserCreationForm

def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('base:home')
    
    if request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')
        
        try:
            user = User.objects.get(email=username)           
        except:
            messages.error(request,'User dose not exist')
            
        user = authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            return redirect('base:home')
        else:
            messages.error(request,'Username or Password is wrong')            
    context={'page':page}
    return render(request,'base/login_register.html',context)

def logoutPage(request):
    logout(request)
    return redirect('base:home')

def registerPage(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('base:home')
        else:
            messages.error(request, 'An error occurred during registration')

    return render(request, 'base/login_register.html', {'form': form})

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(host__username=q)        
    )
    topics = Topic.objects.all()    
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q)|Q(room__host__username=q))[:5]

    rooms_count = rooms.count()

    paginator = Paginator(rooms,5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
  
    context={'page_obj':page_obj,'topics':topics,'rooms_count':rooms_count,
                'room_messages':room_messages,'is_paginated': True if paginator.num_pages > 1 else False}
    return render(request,'base/home.html',context)
 
def room(request,pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all()
    participants  = room.participants.all()
   
    if request.method == 'POST':
        print(request.user)
        message=Message.objects.create(
            user = request.user,
            room = room,
            body = request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('base:room',pk=room.id)
    
    context= {'room':room,'room_messages':room_messages,'participants':participants}
    return render(request,'base/room.html',context)

def userProfile(request,pk):
    p_user = User.objects.get(id=pk)    
    room_messages = p_user.message_set.all()[:5]
    rooms = p_user.room_set.all()
    topics = Topic.objects.all()

    paginator = Paginator(rooms,3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number) 
 
    context= {'page_obj':page_obj,'room_messages':room_messages,
              'topics':topics,'puser':p_user,'is_paginated': True if paginator.num_pages > 1 else False}
    return render(request,'base/profile.html',context)    
    
@login_required(login_url='base:login')
def updateProfile(request):
    user = request.user
    form = UserForm(instance=user)
    if request.method == 'POST':
        form = UserForm(request.POST,instance=user)
        if form.is_valid():
            form.save()
            return redirect('base:user-profile',pk=user.id)
    return render(request,'base/update_profile.html',{'form':form})

@login_required(login_url='base:login')
def createRoom(request):
    form = RoomForm()
    topics=Topic.objects.all()
    
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        
        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
        )
        return redirect('base:home')
    
    context = {
        'form':form,'topics':topics
    }
    return render(request,'base/room_form.html',context)

@login_required(login_url='base:login')
def updateRoom(request,pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)   
    topics = Topic.objects.all() 
    
    if request.user != room.host:
        return HttpResponse('Yore not allowed here')

    if request.method == 'POST':
        topic_name = request.POST.get('topic') 
        # print(topic_name)       
        topic,created = Topic.objects.get_or_create(name=topic_name)
        # print(topic)
        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        return redirect('base:home')
        
    context={'form': form,'room':room,'topics':topics}
    return render(request,'base/room_form.html',context)
    
@login_required(login_url='base:login')
def deleteRoom(request,pk):    
    room = Room.objects.get(id=pk)

    if request.user != room.host:
        return HttpResponse('Yore not allowed here')
    
    if request.method == 'POST':
        room.delete()
        return redirect('base:home')
    
    context = {'obj':room}
    return render(request,'base/delete.html',context)

@login_required(login_url='base:login')
def deleteMessage(request,pk):      
    message = Message.objects.get(id=pk)    

    if request.user != message.user:
        return HttpResponse('Yore not allowed here')
    
    if request.method == 'POST':
        message.delete()
        return redirect('base:home')
    
    context = {'obj':message}
    return render(request,'base/delete.html',context)

def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    context={ 'topics':topics}
    return render(request,'base/topics.html',context)

def activitiesPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''   
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q) |
                                           Q(room__name__icontains=q) |
                                           Q(user__username__icontains=q)
                                           )  

    context={'room_messages':room_messages}
    return render(request,'base/activity.html',context)

base/templates/base/activity_component.html
<div class="activities__header">
    <h2>Recent Activities</h2>
</div>
{% for message in room_messages %}
    <div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a href="{% url 'base:user-profile' message.user.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{{message.user.avatar.url}}" />
        </div>
        <p>
          @{{message.user.name}}
          <span>{{message.created|timesince}} ago</span>
        </p>
      </a>
      <div class="roomListRoom__actions">
        {% if request.user == message.user %}
        <a href="{% url 'base:delete-message' message.id %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>remove</title>
            <path
              d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
            ></path>
          </svg>
        </a>
        {% endif %}
      </div>
    </div>
    <div class="activities__boxContent">
      <p>replied to post “<a href="{% url 'base:room' message.room.id %}">{{message.room}}</a>”</p>
      <div class="activities__boxRoomContent">
        {{message}}
      </div>
    </div>
    </div> 
{% endfor %} 
<div class="activities__box">
  <a class="btn btn--link" href="{% url 'base:activities' %}?q={{puser}}">
    More
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
      <title>chevron-down</title>
      <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
    </svg>
    </a>
</div> 

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}

<h3>Are you sure to delete "{{obj}}".</h3>
<form action="" method="POST">
    {%  csrf_token %}
    <a href="{{ request.META.HTTP_REFERER }} ">GO BACK</a>
    <input type="submit" value="Delete"/>
</form>

{% endblock content %}

base/templates/base/delete_old.html
{% extends 'main.html' %}

{% block content %}

<h3>Are you sure to delete "{{obj}}".</h3>
<form action="" method="POST">
    {%  csrf_token %}
    <a href="{{ request.META.HTTP_REFERER }} ">GO BACK</a>
    <input type="submit" value="Delete"/>
</form>

{% endblock content %}

base/templates/base/delete_room.html
{% extends 'main.html' %}

{% block content %}

<h3>Are you sour to delete this Room: {{room.name}}</h3>
<form action="" method="POST">
    {%  csrf_token %}
    <a href="{{ request.META.HTTP_REFERER }} ">GO BACK</a>
    <input type="submit" value="Delete"/>
</form>

{% endblock content %}

base/templates/base/home.html
{% extends 'main.html' %}

{% block content %}
    <main class="layout layout--3">
      <div class="container" style="margin-bottom: 5rem;">
        <!-- Topics Start -->
        <div class="topics">
          {% include 'base/topics_component.html' %}
          
        </div>
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search" action="{% url 'base:home' %}"  method="GET">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'base:topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url 'base:activities' %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{rooms_count}} Rooms available</p>
            </div>
            <a class="btn btn--main" href="{% url 'base:create-room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>

          {% include 'base/feed_component.html' %}
          
          
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
        <div class="activities">
          {% include 'base/activity_component.html' %}        
        </div>
        <!-- Activities End -->
        
      </div>
    </main>
{% endblock content %}
    

base/templates/base/login_register_old.html
{% extends 'main.html' %}

{% block content %}
{% if page == 'login' %}
<div>
    <h3>LOGIN</h3>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login" id="">
        <p>havent signed up yet? </p>
        <a href="{% url 'base:register' %}">Sing up</a>
    </form>
</div>
{% else %}
<div>
    <h3>REGISTER</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register" id="">
        <p>You alredy signed up</p>
        <a href="{% url 'base:login' %}">Login</a>        
    </form>
</div>
{% endif %}
{% endblock content %}

base/templates/base/paginator.html
{% if page_obj.has_previous %}
    <a class="btn--pill" href="?page=1">&laquo; First</a>
    <a class="btn--pill" href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}
    
{% for num in page_obj.paginator.page_range %}
    {% if num == page_obj.number %}
    <a class="btn btn--info" style="border-radius: 5rem;" href="?page={{num}}">{{num}}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    
        <a class="btn--pill"  href="?page={{num}}">{{num}}</a>
    
    {% endif %}
{% endfor %}
    
{% if page_obj.has_next %}
    <a class="btn--pill" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn--pill" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
{% endif %}

    

base/templates/base/profile.html
{% extends 'main.html' %}

{% block content %}

<main class="profile-page layout layout--3" style="margin-bottom: 5rem;">
    <div class="container">
      <!-- Topics Start -->
      <div class="topics">
        {% include 'base/topics_component.html' %}
      </div>
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="{{puser.avatar.url}}" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{puser.name}}</h3>
            <p>@{{puser.username}}</p>
            {% if request.user == user %}
              <a href="{% url 'base:update-profile' %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% endif %}
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>{{puser.bio}}</p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by {{user}}</a>
            </h2>
          </div>
        </div>
        
       {% include 'base/feed_component.html' %}
        
       <!-- {% include 'base/paginator.html' %} -->
      </div>
      
      <!-- Room List End -->

      <!-- Activities Start -->
      <div class="activities">
        {% include 'base/activity_component.html' %}
      </div>
      <!-- Activities End -->
    </div>
  </main>
{% endblock content %}

base/templates/base/profile_old.html
{% extends 'main.html' %}

{% block content %}
<style>
    .profile-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>
<h2>{{user}}</h2>
<div class="profile-container">
    <div>
        {% include 'base/topics_component.html' %}
    </div>

    <div>
        {% include 'base/feed_component.html' %}
    </div>

    <div>
        {% include 'base/activity_component.html' %}
    </div>
</div>
{% endblock content %}

base/templates/base/room.html
{% extends 'main.html' %}

{% block content %}
    <main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div class="room">
          <div class="room__top">
            <div class="room__topLeft">
              <a href="{{request.META.HTTP_REFERER}}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Study Room</h3>
            </div>

            <div class="room__topRight">
              {% if request.user == room.host %}
              <a href="{% url 'base:update-room' room.id %}">
                <svg
                  enable-background="new 0 0 24 24"
                  height="32"
                  viewBox="0 0 24 24"
                  width="32"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                      />
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                      />
                    </g>
                  </g>
                </svg>
              </a>
              <a href="{% url 'base:delete-room' room.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
              {% endif %}
            </div>

            <!-- <button class="action-button" data-id="120" data-delete-url="https://randomuser.me/api/3324923"
            data-edit-url="profile.html">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>ellipsis-horizontal</title>
              <path
                d="M16 7.843c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 1.98c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
              <path
                d="M16 19.908c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 14.046c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
              <path
                d="M16 31.974c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 26.111c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
              </path>
            </svg>
          </button> -->
          </div>
          <div class="room__box scroll">
            <div class="room__header scroll">

              <div class="room__info">
                <h3>{{room}}</h3>
                <span>{{room.created|timesince}} ago</span>
              </div>
              
              <div class="room__hosted">
                <p>Hosted By</p>
                <a href="{% url 'base:user-profile' room.host.id %}" class="room__author">
                  <div class="avatar avatar--small">
                    <img src="{{room.host.avatar.url}}" />
                  </div>
                  <span>@{{room.host.username}}</span>
                </a>
              </div>
              <!-- <span class="room__topics">{{room.topic}}</span> -->
              
            </div>
            <div class="room__conversation">
              <div class="threads scroll">
                {% for message in room_messages %}
                <div class="thread">
                  <div class="thread__top">
                    <div class="thread__author">
                      <a href="{% url 'base:user-profile' message.user.id %}" class="thread__authorInfo">
                        <div class="avatar avatar--small">
                          <img src="{{message.user.avatar.url}}" />
                        </div>
                        <span>@{{message.user.username}}</span>
                      </a>
                      <span class="thread__date">{{message.created|timesince}} ago</span>
                    </div>
                    {% if request.user == message.user %}
                    <div class="thread__delete">
                      <a href="{% url 'base:delete-message' message.id %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                          <title>remove</title>
                          <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                          ></path>
                        </svg>
                      </a>                      
                    </div>
                    {% endif %}
                  </div>
                  <div class="thread__details">
                    {{message.body}}
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="room__message">
            {% if request.user.is_authenticated %}
            <form action="" method="POST" >
              {% csrf_token %}
              <input name="body"  type="text" placeholder="Write your message here..." />
            </form>
            {% endif %}
          </div>
        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
          <h3 class="participants__top">Participants <span>({{room.participants.all.count}} Joined)</span></h3>
          <div class="participants__list scroll">
            {% for user in participants %}
            <a href="{% url 'base:user-profile' user.id %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="{{user.avatar.url}}" />
              </div>
              <p>
                {{user.name}}
                <span>@{{user.username}}</span>
              </p>
            </a>
            {% endfor %}
          </div>
        </div>
        <!--  End -->
      </div>
    </main>
{% endblock content %}
   

base/templates/base/room_form_old.html
{% extends 'main.html' %}

{% block content %}

<div>
    <form action="" method="POST">
        {% csrf_token %}

        {{form.as_p}}
        
        <input type="submit" value="submit"/>
    </form>
</div>

{% endblock content %}

base/templates/base/topics_component.html
<div class="topics__header">
  <h2>Browse Topics</h2>
</div>
<ul class="topics__list">
  <li>
    <a href="{% url 'base:home' %}" class="active">All <span>{{topics.count}}</span></a>
  </li>
  {% for topic in topics|slice:":5" %}
    <li>
      <a href="{% url 'base:home' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.all.count}}</span></a>      
    </li>
  {% endfor %}
</ul>
<a class="btn btn--link" href="{% url 'base:topics' %}">
  More
  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
    <title>chevron-down</title>
    <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
  </svg>
  </a>




<!-- this codes are old style -->

<!-- <h3>Browse Topics</h3>
    <hr> 
    <div>
        <a href="{% url 'base:home' %}">All</a>
    </div>
        
    <div>
        {% for topic in topics %}
            <a href="{% url 'base:home' %}?q={{topic.name}}">{{topic.name}}</a><br>
        {% endfor%}
    </div> -->